# SQLAlchemy
SQLALCHEMY_DATABASE_URI = 'sqlite:///commands.db'
SQLALCHEMY_TRACK_MODIFICATIONS = False

# Flask
FLASK_SERVER_NAME = '127.0.0.1:8081'
FLASK_DEBUG = True  # It must set to false in Production mode.

# Flask-Restplus
RESTPLUS_SWAGGER_UI_DOC_EXPANSION = 'list'
RESTPLUS_VALIDATE = True
RESTPLUS_MASK_SWAGGER = False
RESTPLUS_ERROR_404_HELP = False
